name: eeg-comet
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - mne==1.8.0
    - eeglabio==0.1.0
    - opencv-python==4.11.0.86
    - onnxruntime==1.19.0
    - pyvista==0.45.2
    - pyvistaqt==0.11.2
    - invertmeeg==0.1.0
    - pyprep==0.4.3
    - seaborn==0.13.2
    - statsmodels==0.14.4
    - PyQt5==5.15.11
    - scikit-learn==1.5.0
    - h5py==3.14.0
    - pandas==2.3.0
