[base]
study_name = xxx
input_folder = /Users/bottlecap/Downloads/OneDrive_1_2023-05-25
channel_location_dir = /Users/bottlecap/Downloads/OneDrive_1_2023-05-25/mbb_channel_location.csv
output_folder = /Users/bottlecap/Downloads/output

[load_new_study]
load_all_files = True
# pattern_content = example_pattern # only when load_all_files is False
extension = .set 
# or .fdt, ...
datatype = raw 
# raw or epoched
filter_data = True
filter_method = fir 
# fir or 'iir' # only when filter_data is True
lowcut_freq = 2 
# only when filter_data is True
highcut_freq = 20 
# only when filter_data is True
downsample_data = True
sample_rate = 250
# only when downsample_data is True
remove_channels = False
# ch2rm = '' # add content in it, only when remove_channels is True

[do_clustering]
smoothing_gfp = True
smoothing_distance = 10 
# only when smoothing_gfp is True
number_of_maps = auto
# or a specific number of maps
kmin = 2
kmax = 10
stopping_mode = gev
# gev or residual or sil
stopping_parameter = 10
# defalt: 10 for 10%
use_percentages = 50
# int, 50/70/100
initializer = Random 
# or "K-Means++"
clustering_method = Modified K-means
max_iterations = 500
clustering_tolerance = 1e-6 
# 1e-6 is default
# clustering_option = 
number_of_repeats = 5 
# 5 is default


[do_backfitting]
backfit_to = all 
# or 'peaks'
filter_segments = True
remove_segments_less_than = 20 
# only when filter_segments is True
filter_segments_option = smooth 
# 'replace_half' or 'remove' or 'replace_high' or 'smooth' # only when filter_segments is True
epsilon = 1e-6
b = 3
lamb = 5

[extract_features]
output_format = .csv 
# or '.pkl' or '.hdf' or '.json'
Features = COV,OCC,MMD
#,TP,LZC,GEV
duration_of_window = 2
# length of window, just for OCC feature

[source_localize_microstates]
inverse_method = dSPM
# or 'MNE', 'sLORETA' 'eLORETA'
nperm = 200
# by default, replace it
spacing = ico3
# or 'oct5', 'ico4', 'oct6', 'ico5'
source_localization_method = avg
# avg or tess

