[base]
study_name = xxx
input_folder = xxx
channel_location_dir = xxx
output_folder = xxx

[load_new_study]
load_all_files = True
# pattern_content = example_pattern # only when load_all_files is False
extension = .set 
# or .fdt, ...
data_type = continuous 
# or "epoched"
filter_data = True
filter_method = fir 
# or 'iir' # only when filter_data is True
lowcut_freq = 2 
# only when filter_data is True
highcut_freq = 20 
# only when filter_data is True
downsample_data = True
sample_rate = 250
# only when downsample_data is True
remove_channels = False
# ch2rm = '' # add content in it, only when remove_channels is True

[do_clustering]
smoothing_gfp = True
smoothing_distance = 10 
# only when smoothing_gfp is True
choose_number_of_maps = user 
# or "auto"
number_of_maps = 5 
# 5 is default
initializer = Random 
# or "K-Means++"
clustering_method = Modified K-means 
clustering_tolerance = 1e-3 
# 1e-3 is default
# clustering_option = 
number_of_repeats = 5 
# 5 is default

[do_backfitting]
backfit_to = all 
# or 'peaks'
filter_segments = True
remove_segments_less_than = 20 
# only when filter_segments is True
filter_segments_option = replace_high 
# or 'replace_half' or 'remove' # only when filter_segments is True

[extract_features]
output_format = .csv 
# or '.pkl' or '.hdf' or '.json'
Features = COV,OCC,MMD,TP,LZC,GEV

[source_localize_microstates]
inverse_method = dSPM
# or 'MNE', 'sLORETA' 'eLORETA'
nperm = 2000
# by default, replace it
spacing = ico3
# or 'oct5', 'ico4', 'oct6', 'ico5'







